# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_Info_Juego.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Juego(object):
    def setupUi(self, Juego):
        Juego.setObjectName("Juego")
        Juego.resize(619, 708)
        self.centralwidget = QtWidgets.QWidget(Juego)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Edit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Edit.setGeometry(QtCore.QRect(350, 300, 75, 23))
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.pushButton_Add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Add.setGeometry(QtCore.QRect(350, 400, 75, 23))
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.pushButton_View = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_View.setGeometry(QtCore.QRect(350, 500, 75, 23))
        self.pushButton_View.setObjectName("pushButton_View")
        self.label_nombre = QtWidgets.QLabel(self.centralwidget)
        self.label_nombre.setGeometry(QtCore.QRect(140, 10, 411, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_nombre.setFont(font)
        self.label_nombre.setText("")
        self.label_nombre.setObjectName("label_nombre")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 260, 221, 341))
        self.tableWidget.setMinimumSize(QtCore.QSize(221, 341))
        self.tableWidget.setMaximumSize(QtCore.QSize(221, 341))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStrikeOut(False)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(105)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(105)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 120, 120))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.png_user = QtWidgets.QLabel(self.frame)
        self.png_user.setGeometry(QtCore.QRect(0, 0, 120, 120))
        self.png_user.setText("")
        self.png_user.setScaledContents(True)
        self.png_user.setObjectName("png_user")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(40, 170, 441, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_juego = QtWidgets.QLabel(self.frame_2)
        self.label_juego.setGeometry(QtCore.QRect(90, 10, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_juego.setFont(font)
        self.label_juego.setText("")
        self.label_juego.setObjectName("label_juego")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 80, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.png_game = QtWidgets.QLabel(self.frame_3)
        self.png_game.setGeometry(QtCore.QRect(1, 1, 78, 78))
        self.png_game.setFrameShape(QtWidgets.QFrame.Box)
        self.png_game.setText("")
        self.png_game.setScaledContents(True)
        self.png_game.setAlignment(QtCore.Qt.AlignCenter)
        self.png_game.setObjectName("png_game")
        Juego.setCentralWidget(self.centralwidget)

        self.retranslateUi(Juego)
        QtCore.QMetaObject.connectSlotsByName(Juego)

    def retranslateUi(self, Juego):
        _translate = QtCore.QCoreApplication.translate
        Juego.setWindowTitle(_translate("Juego", "MainWindow"))
        self.pushButton_Edit.setText(_translate("Juego", "Editar"))
        self.pushButton_Add.setText(_translate("Juego", "Agregar"))
        self.pushButton_View.setText(_translate("Juego", "Ver"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Juego", "Stats"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Juego", "Value"))
